/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.formdev.flatlaf.FlatDarkLaf;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import model.MySQL;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Avishka
 */
public class Student extends javax.swing.JFrame {

    /**
     * Creates new form Student
     */
    public Student() {
        initComponents();
        loadStudents();
       jButton4.setVisible(false);
    }
    
    private void loadStudents(){
        
        try {
            
            ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `student` INNER JOIN `gender` ON `student`.`gender_id`=`gender`.`id`"
                    + " ");
            
            DefaultTableModel Deftable = (DefaultTableModel)jTable1.getModel();
                           Deftable.setRowCount(0);
            
            while(resultSet.next()){
               
               Vector vector = new Vector();
                  vector.add(resultSet.getString("first_name"));
                  vector.add(resultSet.getString("last_name"));
                  vector.add(resultSet.getString("birth_day"));
                  vector.add(resultSet.getString("id"));
                  vector.add(resultSet.getString("gender.name"));
                  
                  Deftable.addRow(vector);
                                       
            }
            
            jTable1.setModel(Deftable);                                  
            
        } catch (Exception e) {
          JOptionPane.showMessageDialog(this, "Internal Error Appeared Please Try Again Error"+e, "Error", JOptionPane.ERROR_MESSAGE);
        }
               
    }
    
    public void resetField(){
      
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            
            buttonGroup1.clearSelection();
            buttonGroup2.clearSelection();
         
              
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane9 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Student Management");

        jLabel2.setText("Register or Remove a Student");

        jLabel3.setText("First Name");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Last Name");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Birth Day");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel6.setText("Student ID");

        jLabel7.setText("Parent Information");

        jLabel8.setText("Name ");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel9.setText("NIC");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel10.setText("Contact ");

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jLabel11.setText("Address");

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Add-Up");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Birth Day", "Student ID", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel12.setText("Find Student ");

        jButton5.setText("Find");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel13.setText("Enter Student ID");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Birsth Day", "Student ID", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane10.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setResizable(false);
            jTable3.getColumnModel().getColumn(1).setResizable(false);
            jTable3.getColumnModel().getColumn(2).setResizable(false);
            jTable3.getColumnModel().getColumn(3).setResizable(false);
            jTable3.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel22.setText("Student Table");

        jLabel23.setText("Parent Information");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "NIC", "Address", "Contact", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane11.setViewportView(jTable4);
        if (jTable4.getColumnModel().getColumnCount() > 0) {
            jTable4.getColumnModel().getColumn(0).setResizable(false);
            jTable4.getColumnModel().getColumn(1).setResizable(false);
            jTable4.getColumnModel().getColumn(2).setResizable(false);
            jTable4.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel15.setText("Gender");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Male");
        jRadioButton1.setActionCommand("1");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Female");
        jRadioButton2.setActionCommand("2");

        jLabel16.setText("Gender");

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("Male");
        jRadioButton3.setActionCommand("1");

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("female");
        jRadioButton4.setActionCommand("2");

        jLabel17.setText("Fill all Information and Press Add-up to Register a New Student");

        jLabel18.setText("Use Student ID for Update Details or Remove a Student ");

        jLabel19.setText("Use Only Numbers to Create the Student Id");

        jButton4.setText("Update Data");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Teacher Add Up");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Emp Add Up");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(126, 126, 126)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel4)
                                .addGap(147, 147, 147)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(139, 139, 139)
                                .addComponent(jLabel10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(140, 140, 140)
                                .addComponent(jLabel11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel15)
                                .addGap(171, 171, 171)
                                .addComponent(jLabel16)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jButton5))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2)
                        .addGap(71, 71, 71)
                        .addComponent(jRadioButton3)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButton4)
                        .addGap(86, 86, 86)
                        .addComponent(jLabel14)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel12)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel13)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel22)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel17)
                .addGap(2, 2, 2)
                .addComponent(jLabel18)
                .addGap(2, 2, 2)
                .addComponent(jLabel19)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      
//    Student Data    
       String FirstName =  jTextField1.getText();
       String LastName =  jTextField2.getText();
       String BirthDay =  jTextField3.getText();
       String StudentId =  jTextField4.getText();      
       ButtonModel StudentGender = buttonGroup1.getSelection();
//      Parent Data 
        String Name  = jTextField5.getText();
        String NIC  = jTextField6.getText();
        String Contact  = jTextField7.getText();
        String Address  = jTextField8.getText();
        ButtonModel parentGender = buttonGroup2.getSelection();
        
         if(FirstName.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Enter Student First Name", "Alert", JOptionPane.ERROR_MESSAGE);
        }else if(LastName.isEmpty()){
              JOptionPane.showMessageDialog(this, "Please Enter Student Last Name", "Alert", JOptionPane.ERROR_MESSAGE);
        }else if(BirthDay.isEmpty()){
              JOptionPane.showMessageDialog(this, "Please Enter Student Birth Day", "Alert", JOptionPane.ERROR_MESSAGE);  
        }else if(BirthDay.length() >8 ){      
            JOptionPane.showMessageDialog(this, "Invalid Format Enter Birthday without Using Special Characters"
                    + " If Birthday - 2001/01/12 Type it as 20010112 ", "Alert", JOptionPane.ERROR_MESSAGE);
        }else if(StudentId.isEmpty()){
              JOptionPane.showMessageDialog(this, "Please Enter Student Id", "Alert", JOptionPane.ERROR_MESSAGE);            
        }else if(StudentGender == null){
              JOptionPane.showMessageDialog(this, "Please Select Student Gender", "Alert", JOptionPane.ERROR_MESSAGE);
        }else if(Name.isEmpty()){
              JOptionPane.showMessageDialog(this, "Please Enter Parent Name", "Alert", JOptionPane.ERROR_MESSAGE);
        }else if(NIC.isEmpty()){
              JOptionPane.showMessageDialog(this, "Please Enter Parent NIC", "Alert", JOptionPane.ERROR_MESSAGE);
        }else if(NIC.length()>15){
               JOptionPane.showMessageDialog(this, "Invalid NIC", "Alert", JOptionPane.ERROR_MESSAGE);
        }else if(Contact.isEmpty()){
              JOptionPane.showMessageDialog(this, "Please Enter Parent Contact Number", "Alert", JOptionPane.ERROR_MESSAGE);      
        }else if(Contact.length()>10){    
              JOptionPane.showMessageDialog(this, "Contact Number is Invalid", "Alert", JOptionPane.ERROR_MESSAGE); 
        }else if(Address.isEmpty()){
              JOptionPane.showMessageDialog(this, "Please Enter Parent Address", "Alert", JOptionPane.ERROR_MESSAGE);         
        }else if(parentGender == null){
              JOptionPane.showMessageDialog(this, "Please Select Parent Gender", "Alert", JOptionPane.ERROR_MESSAGE);
        }else{
            
                
            String studentgender = StudentGender.getActionCommand();
            String parentgender = parentGender.getActionCommand();
            
            try{ 
                
             Integer integerStudent = MySQL.executeIUD("INSERT INTO `student` (`id`,`first_name`,`last_name`,`birth_day`,`gender_id`) VALUES ('"+StudentId+"','"+FirstName+"'"
                     + ",'"+LastName+"','"+BirthDay+"','"+studentgender+"')  ");
             
             Integer integerParent = MySQL.executeIUD("INSERT INTO `parent` (`name`,`nic`,`address`,`contact`,`gender_id`,`Student_id`) VALUES ('"+Name+"','"+NIC+"'"
                     + ",'"+Address+"','"+Contact+"','"+parentgender+"','"+StudentId+"')");
                
                  JOptionPane.showMessageDialog(this, "Registration Success", "Success", JOptionPane.PLAIN_MESSAGE);
                  loadStudents();
                  resetField();
                
                
            } catch (Exception e) {
              JOptionPane.showMessageDialog(this, "Invalid Request Please Try Again Check Infomation Again", "Alert", JOptionPane.ERROR_MESSAGE);
                            
                       
            }
            
            
            
            
            
            
        }
        
       
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
       jTextField2.grabFocus();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        jTextField3.grabFocus();
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        jTextField4.grabFocus();
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
       jTextField6.grabFocus();
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        jTextField7.grabFocus();
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
       jTextField8.grabFocus();
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        jTextField9.grabFocus();
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
            String  StudentId = jTextField4.getText();
           
            if(StudentId.isEmpty()){
                JOptionPane.showMessageDialog(this, "Please Enter Student Id", "Alert", JOptionPane.ERROR_MESSAGE);
            }else{
                
                try {
                    
                    ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `student` INNER JOIN `parent` "
                            + " ON `parent`.`Student_id` = `student`.`id`  WHERE `student`.`id`='"+StudentId+"' ");
                    if(resultSet.next()){
                         
                        String FirstName = resultSet.getString("first_name");
                        String LastName = resultSet.getString("last_name");
                        String BirthDay = resultSet.getString("birth_day");
                        String Gender = String.valueOf(resultSet.getInt("gender_id"));
                        
                        String Name = resultSet.getString("name");
                        String NIC = resultSet.getString("nic");
                        String Address = resultSet.getString("address");
                        String Contact = resultSet.getString("contact");
                       String parentGender = String.valueOf(resultSet.getInt("gender_id"));
                        
                        jTextField1.setText(String.valueOf(FirstName));
                        jTextField2.setText(String.valueOf(LastName));
                        jTextField3.setText(String.valueOf(BirthDay));
                        jTextField5.setText(String.valueOf(Name));
                        jTextField6.setText(String.valueOf(NIC));
                        jTextField7.setText(String.valueOf(Address));
                        jTextField8.setText(String.valueOf(Contact));
                        
                        if(Gender.equals("1")){
                            jRadioButton1.setSelected(true);
                        }else{
                            jRadioButton2.setSelected(true);
                        }
                        
                        if(parentGender.equals("1")){
                            jRadioButton3.setSelected(true);
                        }else{
                            jRadioButton4.setSelected(true);
                        }
                        
                        jButton3.setVisible(false);
                        jButton4.setVisible(true);
                        jTextField4.disable();
                        
                        
        
            
      
                                                                                                                            
                    }else{     
                      
                        JOptionPane.showMessageDialog(this, "Invalid Student Id or Student Doesn't Exists", "Alert", JOptionPane.ERROR_MESSAGE);
                    }
                    
                    
                } catch (Exception e) {
                  JOptionPane.showMessageDialog(this, "Internal Error Appeared Please Try Again Error"+e, "Error", JOptionPane.ERROR_MESSAGE);
                }
                
            }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
             
         
//    Student Data    
       String FirstName =  jTextField1.getText();
       String LastName =  jTextField2.getText();
       String BirthDay =  jTextField3.getText();
       String StudentId =  jTextField4.getText();      
       ButtonModel StudentGender = buttonGroup1.getSelection();
//      Parent Data 
        String Name  = jTextField5.getText();
        String NIC  = jTextField6.getText();
        String Contact  = jTextField7.getText();
        String Address  = jTextField8.getText();
        ButtonModel parentGender = buttonGroup2.getSelection();
        
        if(FirstName.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Enter Student First Name", "Alert", JOptionPane.ERROR_MESSAGE);
        }else if(LastName.isEmpty()){
              JOptionPane.showMessageDialog(this, "Please Enter Student Last Name", "Alert", JOptionPane.ERROR_MESSAGE);
        }else if(BirthDay.isEmpty()){
              JOptionPane.showMessageDialog(this, "Please Enter Student Birth Day", "Alert", JOptionPane.ERROR_MESSAGE);  
        }else if(BirthDay.length() >=8 && BirthDay.length() <=8 ){      
            JOptionPane.showMessageDialog(this, "Invalid Format Enter Birthday without Using Special Characters"
                    + " If Birthday - 2001/01/12 Type it as 20010112 ", "Alert", JOptionPane.ERROR_MESSAGE);
        }else if(StudentId.isEmpty()){
              JOptionPane.showMessageDialog(this, "Please Enter Student Id", "Alert", JOptionPane.ERROR_MESSAGE);            
        }else if(StudentGender == null){
              JOptionPane.showMessageDialog(this, "Please Select Student Gender", "Alert", JOptionPane.ERROR_MESSAGE);
        }else if(Name.isEmpty()){
              JOptionPane.showMessageDialog(this, "Please Enter Parent Name", "Alert", JOptionPane.ERROR_MESSAGE);
        }else if(NIC.isEmpty()){
              JOptionPane.showMessageDialog(this, "Please Enter Parent NIC", "Alert", JOptionPane.ERROR_MESSAGE);
        }else if(NIC.length()>15){
               JOptionPane.showMessageDialog(this, "Invalid NIC", "Alert", JOptionPane.ERROR_MESSAGE);
        }else if(Contact.isEmpty()){
              JOptionPane.showMessageDialog(this, "Please Enter Parent Contact Number", "Alert", JOptionPane.ERROR_MESSAGE);      
        }else if(Contact.length()>10){    
              JOptionPane.showMessageDialog(this, "Contact Number is Invalid", "Alert", JOptionPane.ERROR_MESSAGE); 
        }else if(Address.isEmpty()){
              JOptionPane.showMessageDialog(this, "Please Enter Parent Address", "Alert", JOptionPane.ERROR_MESSAGE);         
        }else if(parentGender == null){
              JOptionPane.showMessageDialog(this, "Please Select Parent Gender", "Alert", JOptionPane.ERROR_MESSAGE);
        }else{
            
                
            
           String studentgender = StudentGender.getActionCommand();
           String parentgender = parentGender.getActionCommand(); 
     
               
           
            try {
                
                 Integer StuUp = MySQL.executeIUD("UPDATE `student` SET `id`='"+StudentId+"',`first_name`='"+FirstName+"', `last_name`='"+LastName+"', "
                         + " `birth_day`='"+BirthDay+"', `gender_id`='"+studentgender+"'  WHERE `id`= '"+StudentId+"' ");
                
                 Integer ParUp = MySQL.executeIUD(" UPDATE `parent` INNER JOIN `student` ON `parent`.`student_id` = `student`.`id` SET `name`='"+Name+"'"
                         + ",  `nic`='"+NIC+"', `address`='"+Address+"', `contact`='"+Contact+"', `parent`.`gender_id`='"+parentgender+"', `Student_id`='"+StudentId+"' "
                                 + "  WHERE `Student_id`= '"+StudentId+"' ");
                 
                 JOptionPane.showMessageDialog(this, "Update Successfull !", "Success", JOptionPane.PLAIN_MESSAGE);
                
                  jButton3.setVisible(true);
                  jButton4.setVisible(false);
                  jTextField4.enable();
                 loadStudents();
                 resetField();
                
                
                
                
            } catch (Exception e) {
              JOptionPane.showMessageDialog(this, "Internal Error Appeared Please Try Again Error"+e, "Error", JOptionPane.ERROR_MESSAGE);
            }
           
           
        }
                     
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        String StudentId = jTextField4.getText();
        
        if(StudentId.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please Enter Student ID to Remove the Student", "Alert", JOptionPane.ERROR_MESSAGE);
            
        }else{
            
            try {
                
                  ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `student` INNER JOIN `parent` "
                            + " ON `parent`.`Student_id` = `student`.`id`  WHERE `student`.`id`='"+StudentId+"' ");
                
                  if(resultSet.next()){
                      jTextField4.disable();
                      Integer deletePar = MySQL.executeIUD(" DELETE FROM `parent` WHERE parent.Student_id='"+StudentId+"' ");
                      Integer deleteStu = MySQL.executeIUD(" DELETE FROM `student` WHERE student.id='"+StudentId+"' ");
                     
                      
                        loadStudents();
                        resetField();
                        jTextField4.enable();
                        JOptionPane.showMessageDialog(this, "Remove Successfull !", "Success", JOptionPane.PLAIN_MESSAGE);
                        
                      
                      
                      
                      
                  }else{
                     JOptionPane.showMessageDialog(this, "Invalid Student ID or Student doesn't Exists ", "Alert", JOptionPane.ERROR_MESSAGE);
                  }
                
            } catch (Exception e) {
          JOptionPane.showMessageDialog(this, "Internal Error Appeared Please Try Again Error"+e, "Error", JOptionPane.ERROR_MESSAGE);
             }
            
            
            
            
            
        }
        
        
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       
        String StudentId = jTextField9.getText();
        
        if(StudentId.isEmpty()){
                JOptionPane.showMessageDialog(this, "Please Enter Student ID !", "Alert", JOptionPane.ERROR_MESSAGE);
                jTextField9.grabFocus();
        }else{
            
            try {
                
                    ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `student` INNER JOIN `parent` "
                            + " ON `parent`.`Student_id` = `student`.`id` "
                            + "INNER JOIN `gender` ON `student`.`gender_id`=`gender`.`id`  WHERE `student`.`id`='"+StudentId+"' ");
                
                    if(resultSet.next()){
                        
                          DefaultTableModel Deftable = (DefaultTableModel)jTable3.getModel();
                          Deftable.setRowCount(0);
                         
                  Vector Stuvector = new Vector();
                  Stuvector.add(resultSet.getString("first_name"));
                  Stuvector.add(resultSet.getString("last_name"));
                  Stuvector.add(resultSet.getString("birth_day"));
                  Stuvector.add(resultSet.getString("id"));
                  Stuvector.add(resultSet.getString("gender.name"));
                  
                  Deftable.addRow(Stuvector);
                  jTable3.setModel(Deftable);
                             
                          DefaultTableModel ParentDeftable = (DefaultTableModel)jTable4.getModel();
                          ParentDeftable.setRowCount(0);
                          
                         Vector ParentVector = new Vector();
                         
                        ParentVector.add(resultSet.getString("name"));
                        ParentVector.add(resultSet.getString("nic"));
                        ParentVector.add(resultSet.getString("address"));
                        ParentVector.add(resultSet.getString("contact"));
                        ParentVector.add(resultSet.getString("gender.name"));
                        
                       ParentDeftable.addRow(ParentVector);
                       jTable4.setModel(ParentDeftable);
                                                                          
                    }else{                      
                        JOptionPane.showMessageDialog(this, "inavlid Student Id or Student Doesn't Exists !", "Alert", JOptionPane.ERROR_MESSAGE);                       
                    }
                
                
                
            } catch (Exception e) {
              JOptionPane.showMessageDialog(this, "Internal Error Appeared Please Try Again Error"+e, "Error", JOptionPane.ERROR_MESSAGE);
            }
            
            
            
        }
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        Teacher teach = new Teacher();
         teach.setVisible(true);
         this.dispose();
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       Employee emp = new Employee();
        emp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatDarkLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
